# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='flashboard',
    version='0.1.0',
    python_requires='==3.*,>=3.7.0',
    author='robinmin',
    author_email='luonbin@hotmail.com',
    packages=['flashboard'],
    package_data={
        'flashboard': [
            'static/images/*.png', 'templates/*.html', 'translations/*.pot',
            'translations/zh_Hans_CN/LC_MESSAGES/*.mo',
            'translations/zh_Hans_CN/LC_MESSAGES/*.po'
        ]
    },
    install_requires=[
        'celery==4.*,>=4.3.0', 'flask==1.*,>=1.1.0', 'flask-admin==1.*,>=1.5.0',
        'flask-babel==0.*,>=0.12.2', 'flask-cors==3.*,>=3.0.0',
        'flask-login==0.*,>=0.4.1', 'flask-mail==0.*,>=0.9.1',
        'flask-migrate==2.*,>=2.5.0', 'flask-restplus==0.*,>=0.13.0',
        'flask-script==2.*,>=2.0.0', 'flask-sqlalchemy==2.*,>=2.4.0',
        'flask-wtf==0.*,>=0.14.2', 'gunicorn==19.*,>=19.9.0',
        'passlib==1.*,>=1.7.0', 'psycopg2==2.*,>=2.8.0', 'pyjwt==1.*,>=1.7.0',
        'sentry-sdk==0.13.0'
    ],
    extras_require={
        'dev': [
            'autopep8==1.*,>=1.4.0', 'flask-debugtoolbar==0.*,>=0.10.1',
            'flask-sqlacodegen==1.*,>=1.1.0', 'pytest==3.*,>=3.0.0',
            'pytest-cov==2.*,>=2.8.0'
        ]
    },
)
