"""empty message

Revision ID: 1fee8919d2fa
Revises: 
Create Date: 2019-10-21 13:37:36.981150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fee8919d2fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_name', table_name='users')
    op.drop_table('users')
    op.drop_table('roles_users')
    op.drop_table('token_mgr')
    op.drop_table('role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('token_mgr',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('create_on', sa.DATETIME(), nullable=False),
    sa.Column('expiry_on', sa.DATETIME(), nullable=False),
    sa.Column('first_access_on', sa.DATETIME(), nullable=True),
    sa.Column('last_access_on', sa.DATETIME(), nullable=True),
    sa.Column('access_count', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.INTEGER(), nullable=False),
    sa.Column('token', sa.VARCHAR(length=172), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('roles_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password', sa.VARCHAR(length=64), nullable=False),
    sa.Column('private_salt', sa.VARCHAR(length=64), nullable=False),
    sa.Column('actived', sa.BOOLEAN(), nullable=True),
    sa.Column('authenticated', sa.BOOLEAN(), nullable=True),
    sa.Column('last_login_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login_ip', sa.VARCHAR(length=100), nullable=True),
    sa.Column('current_login_at', sa.DATETIME(), nullable=True),
    sa.Column('current_login_ip', sa.VARCHAR(length=100), nullable=True),
    sa.Column('login_count', sa.INTEGER(), nullable=False),
    sa.Column('signup_at', sa.DATETIME(), nullable=True),
    sa.Column('confirmed_at', sa.DATETIME(), nullable=True),
    sa.CheckConstraint('actived IN (0, 1)'),
    sa.CheckConstraint('authenticated IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_name', 'users', ['name'], unique=1)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    # ### end Alembic commands ###
